[workspace]
members = ["macros"]

[package]
name = "effie"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
authors = ["Federico Maria Morrone <contact@morrone.dev>"]
description = "Idiomatic api to uefi"
documentation = "https://docs.rs/effie"
repository = "https://github.com/bread-bootloader/bread"
include = ["src/**/*.rs", "README.md", "LICENSE"]
readme = "README.md"

[dependencies]
bitflags = "2.6.0"
uguid = "2.2.0"
itoa = "1.0.11"
effie-macros = { version = "0.0.1", path = "macros" }
